version: v28.1.0

files:
  - .github/workflows/poetry-release.yaml
  - .github/workflows/verify-release.yaml
  - .github/.kodiak.toml
  - .autorc.json

values:
  gitOpsEnabled: true
  allowKodiakAutoMerge: true
